### ISSUE TITLE
contour循环之后number是空的，想问一下具体是什么原因。

### ISSUE THREAD

**Issue by baimuchu** [SakuraHentai/nursery-bot#1]
![屏幕截图 2024-01-04 181959](https://github.com/SakuraHentai/nursery-bot/assets/61861907/961909a2-caf2-49f4-ab70-5ab42a1b618d)

contour应该是识别出来了，但是number感觉是没有提取出来。这是由于显示屏的分辨率嘛？还是什么其他原因呀。
然后比较想了解一下config里面的参数是什么意思呀。
我看debug.png和screenshot.png导出是没有问题的。
感谢！

**Comment by SakuraHentai** [comment]
Hello, 可试试最新代码, 如果还是不行可以提供一下游戏截图, 我这边没有2560分辨率的环境

另已补充config中的说明在README.~

**Comment by baimuchu** [comment]
谢谢，我解决了！不过貌似tesseract的使用路径可能会有点麻烦。可以在README里面提及一下。再次感谢。
以及提一个建议是如果bot认为没有可以消除的话，感觉就可以结束loop了。

**Comment by SakuraHentai** [comment]
> 谢谢，我解决了！不过貌似tesseract的使用路径可能会有点麻烦。可以在README里面提及一下。再次感谢。 以及提一个建议是如果bot认为没有可以消除的话，感觉就可以结束loop了。

解决了就好~, 有空我看看结束 loop, 顺便再加上 tesseract path的补充. 谢谢你的建议. 😁
