### ISSUE TITLE
OCR识别失败

### ISSUE THREAD

**Issue by Nick0223** [SakuraHentai/nursery-bot#5]
前提：都已安装，系统变量已添加

输出：
PS C:\Program Files\Tesseract-OCR> python C:\Users\王宇\Downloads\nursery-bot-main\entry.py
OCR seems to have failed
No chessboard found

**Comment by Nick0223** [comment]
![Uploading Snipaste_2024-02-13_00-57-33.png…]()

**Comment by Nick0223** [comment]
![Uploading Snipaste_2024-02-13_00-57-33.png…]()

**Comment by Nick0223** [comment]
似乎是识别率的问题，多次尝试有时能够正常识别...

**Comment by SakuraHentai** [comment]
Hello，你可以看下目录里debug的图，看看有没有什么遮挡到了游戏数字区域。
