### ISSUE TITLE
OCR seems to have failed No chessboard found

### ISSUE THREAD

**Issue by zhangshiqi-hub** [SakuraHentai/nursery-bot#6]
哥，为啥我这个老报这个错误呀
OCR seems to have failed
No chessboard found

**Comment by SakuraHentai** [comment]
看下debug.png有没有被遮挡?

**Comment by zhangshiqi-hub** [comment]
没有诶
![Uploading 微信截图_20240322160957.png…]()
有时候OK 大部分时候报错

**Comment by zhangshiqi-hub** [comment]
没有诶
![Uploading 微信截图_20240322160957.png…]()
有时候OK 大部分时候报错

**Comment by zhangshiqi-hub** [comment]
![微信截图_20240322164623](https://github.com/SakuraHentai/nursery-bot/assets/65799457/fc064d1f-385a-4d53-b957-1ee674438436)
发现了OCR好像没有把最后一个数字识别

**Comment by SakuraHentai** [comment]
试试换换tesseract的参数, 还有tesseract版本是最新的吗?

**Comment by zhangshiqi-hub** [comment]
还是OCR识别效果的问题，很多时候识别的数字不是160，tesseract是最新的，试着换了一下参数和对图片去噪，效果提升不大，解决办法就只能多开几局

**Comment by SakuraHentai** [comment]
奇怪, 复现不了.. 失败的图分辨率多少? 发上来我试试 debug的.

**Comment by zhangshiqi-hub** [comment]
![debug](https://github.com/SakuraHentai/nursery-bot/assets/65799457/3df062d0-d692-435e-8c1b-ccaf05502c3f)
![screenshot](https://github.com/SakuraHentai/nursery-bot/assets/65799457/aef2bcc8-fca8-4512-b6af-2726d58aa26d)
可能是分辨率低了，这个图识别出来就只有129

**Comment by rikkayoru** [comment]
尝试下使用最新代码~
